# Generated by Django 3.2.3 on 2021-06-13 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='photo',
            field=models.ImageField(max_length=255, upload_to='images/'),
        ),
    ]
