# Generated by Django 3.2.3 on 2021-05-30 04:28

import app.schema
from django.db import migrations
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_supply_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=enumfields.fields.EnumField(default='哩哩扣扣', enum=app.schema.Category, max_length=10),
        ),
    ]
