# Generated by Django 3.2.3 on 2021-06-06 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='line_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='supply',
            name='phone_num',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
